name: Publish Tauri App

on:
  push:
    branches: [main]

jobs:
  publish-tauri:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        args:
          - '--target x86_64-unknown-linux-gnu'
          - '--target i686-unknown-linux-gnu'

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          profile: minimal
          toolchain: stable

      - name: Install Dependencies
        run: npm install

      - name: Build Tauri App
        uses: tauri-apps/tauri-action@v1
        with:
          target: ${{ matrix.args }}

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v0.1.0  # Replace with your desired version
          release_name: 'Code-Seddik v0.1.0'  # Replace with your desired name
          draft: false  # Set to true for draft releases
          prerelease: false  # Set to true for pre-releases
          body: |
            This is the latest release of Code-Seddik.
            Check out the release notes for more details.

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Code-Seddik
          path: target/release/bundle
